In [1]:
import numpy as np

In [6]:
a=np.random.randint(0,100,20)
a

array([61, 68, 69, 96, 61, 84, 84, 35, 76, 47, 24, 32, 68, 51, 95, 88, 32,
       94, 31,  4])

In [7]:
a%2 ==0

array([False,  True, False,  True, False,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True])

In [9]:
a[a%2==0]

array([68, 96, 84, 84, 76, 24, 32, 68, 88, 32, 94,  4])

In [10]:
a[(a%2==0)&(a>50)]

array([68, 96, 84, 84, 76, 68, 88, 94])

In [11]:
a[(a%2==0)|(a>50)]

array([61, 68, 69, 96, 61, 84, 84, 76, 24, 32, 68, 51, 95, 88, 32, 94,  4])

In [13]:
d=np.loadtxt("example", delimiter=',')
d

array([[ 2.4, 21. , 31. ],
       [ 2.4, 22. , 31. ],
       [ 3.3, 17. , 28. ],
       [ 1.2, 43. , 23. ],
       [ 3.4, 19. , 32. ]])

In [14]:
d==31

array([[False, False,  True],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
d[d==31]

array([31., 31.])

In [16]:
np.where(d==31)

(array([0, 1]), array([2, 2]))

In [17]:
d[:,0]

array([2.4, 2.4, 3.3, 1.2, 3.4])

In [18]:
d[:,0] >3

array([False, False,  True, False,  True])

In [25]:
(d[:,2]>3)&(d[:,1]>20)

array([ True,  True, False,  True, False])