In [6]:
import numpy as np
print(np.__version__)

1.16.2


In [9]:
a=np.arange(0,11) *10
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
# for n in a:
#     print(n)

In [18]:
for i,v in enumerate(a,start=1):
    print(i,v)

1 0
2 10
3 20
4 30
5 40
6 50
7 60
8 70
9 80
10 90
11 100


In [20]:
b=np.reshape(np.arange(1,21),(4,5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
for _ in b:
    print(_)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [23]:
for _ in b.flat:
    print(_)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [27]:
for i,v in np.ndenumerate(b):
    print(i,v)
    

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
(2, 0) 11
(2, 1) 12
(2, 2) 13
(2, 3) 14
(2, 4) 15
(3, 0) 16
(3, 1) 17
(3, 2) 18
(3, 3) 19
(3, 4) 20


In [29]:
c=np.arange(1,31).reshape(2,3,5)
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [33]:
 for i,v in np.ndenumerate(c):
        print(i,v)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15
(1, 0, 0) 16
(1, 0, 1) 17
(1, 0, 2) 18
(1, 0, 3) 19
(1, 0, 4) 20
(1, 1, 0) 21
(1, 1, 1) 22
(1, 1, 2) 23
(1, 1, 3) 24
(1, 1, 4) 25
(1, 2, 0) 26
(1, 2, 1) 27
(1, 2, 2) 28
(1, 2, 3) 29
(1, 2, 4) 30
