In [1]:
import numpy as np

In [2]:
a=np.array([[1,1],[1,5]])

In [3]:
b=np.array([[90],[250]])

In [4]:
aa=np.linalg.inv(a)
aa

array([[ 1.25, -0.25],
       [-0.25,  0.25]])

In [5]:
np.dot(aa,b)

array([[50.],
       [40.]])

In [6]:
aa@b

array([[50.],
       [40.]])

In [7]:
A=np.matrix([[1,1],[1,5]])
A

matrix([[1, 1],
        [1, 5]])

In [8]:
B=np.matrix([[90],[250]])
B

matrix([[ 90],
        [250]])

In [9]:
AI=A.i
A

matrix([[1, 1],
        [1, 5]])