In [2]:
import numpy as np
id="400638133393x"

In [6]:
a=np.array(list(id[:12]),dtype=int)
a

array([4, 0, 0, 6, 3, 8, 1, 3, 3, 3, 9, 3])

In [13]:
b=np.tile([1,3],6)
b

array([1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3])

In [14]:
c=a*b
c

array([ 4,  0,  0, 18,  3, 24,  1,  9,  3,  9,  9,  9])

In [17]:
d=np.sum(c)
d

89

In [19]:
xid = 0 if d % 10 == 0 else 10 -(d%10)
xid

1

In [21]:
def checkdigit(id):
    d=np.sum(np.array(list(id[:12]),dtype=int)*np.tile([1,3],6))
    return 0 if d % 10 == 0 else 10 -(d%10)

In [22]:
print(checkdigit("400638133393"))

1
