In [18]:
import numpy as np

In [4]:
age = [12,34,32,45]

In [5]:
a=np.array([age])
a

array([[12, 34, 32, 45]])

In [10]:
b=np.arange(1,51)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
c=np.reshape(b,(5,10))
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [14]:
o=np.zeros((4,6))
o

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
o[:]=9
o

array([[9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.]])

In [17]:
e=np.eye(5,6)
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])