In [29]:
import numpy as np
a=np.reshape(np.arange(1,21),(-1,5))


In [28]:
b =np.reshape(np.arange(20,40),(4,5))


In [30]:
c=np.vstack([a,b])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [27]:
d=np.hstack((a,b))


In [24]:
e=np.hsplit(d,5)

In [25]:
e[0]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [35]:
e=np.vsplit(c,4)


[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]), array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])]

In [36]:
e[2]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [38]:
e[:2]

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])]

In [47]:
f=np.arange(1,5)
h=np.arange(5,9)

In [48]:
g=np.stack((f,h),axis=1)

In [49]:
g

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])